### ISSUE TITLE
No module named cython_bbox ?

### ISSUE THREAD

**Issue by BioITWorker** [YiYuanIntelligent/3DFasterRCNN_LungNoduleDetector#3]
hi,楼主：
请教个问题，最近学习caffe，尝试搭建你的代码，运行的时候发现个小问题，lib/roi_data_layer/roidb.py脚本中报了ImportError: No module named cython_bbox错误，原因是util目录下没有cython_bbox程序，所以我导入blob.py替换了cython_bbox，但是出现报错
![default](https://user-images.githubusercontent.com/29221718/33755862-c265d9a6-dc2d-11e7-8c66-c0662b019f50.png)，请楼主帮忙，谢谢！！

**Comment by Hitiron** [comment]
这个项目 是要用intel的caffe才能跑起来的,原因是项目中用到的层都是3D的,而原生caffe不支持3D层,所以你如果是用BVLC的caffe就会出现这个问题. 但是如果用项目要求的intel caffe的话,我在本机跑非常慢,不知道题主 是如何解决的?@mystao

**Comment by mystao** [comment]
实际上我也安装了inter 版本的caffe，但是速度太慢，我用两张Intel(R) Xeon(R) CPU E5-2690跑模型，半小时才迭代一次，作者是怎么解决速度问题的？，请赐教多谢

**Comment by BioITWorker** [comment]
确实改用inter caffe 可以跑起来，我两张Intel(R) Xeon(R) CPU E5-2690 0这边训练30m迭代一次，太慢了。作者参赛的时候怎么做到速度可以4sample/s的，谢谢
